repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: flake8
        exclude: ^src/ci_scripts/
-   repo: local
    hooks:
    -   id: eslint
        name: eslint
        entry: eslint -c src/.eslintrc
        language: node
        'types': [javascript]
        files: 'src/wirecloud/(commons|platform)/static/js/.*'
